// IMPORTANT: This file is automatically generated and should not be edited manually.

export * from './src/js/index.js';
export * from './src/js/ReviewForm.js';
export * from './src/js/ReviewsCarousel.js';

export * from './src/templates/Review.soy';
export * from './src/templates/ReviewForm.soy';
export * from './src/templates/Reviews.soy';
