// IMPORTANT: This file is automatically generated and should not be edited manually.

export * from './src/templates/Phone.soy';
export * from './src/templates/Phones.soy';
export * from './src/templates/ProfilePhoneCounter.soy';
