// IMPORTANT: This file is automatically generated and should not be edited manually.

export * from './src/js/Accordion.js';

export * from './src/templates/Accordion.soy';
export * from './src/templates/AspectRatio.soy';
