// IMPORTANT: This file is automatically generated and should not be edited manually.

export * from './src/templates/Address.soy';
export * from './src/templates/Fields.soy';
export * from './src/templates/I18n.soy';
export * from './src/templates/I18nDemo.soy';
