// IMPORTANT: This file is automatically generated and should not be edited manually.

export * from './src/js/Modal.js';
export * from './src/js/ModalManager.js';

export * from './src/templates/Modal.soy';
