// IMPORTANT: This file is automatically generated and should not be edited manually.

export * from './src/templates/Icon.soy';
export * from './src/templates/Links.soy';
export * from './src/templates/ShareButton.soy';
